# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gerador(object):
    def setupUi(self, Gerador):
        Gerador.setObjectName("Gerador")
        Gerador.resize(974, 564)
        self.centralWidget = QtWidgets.QWidget(Gerador)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 300, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.abrir_modelo = QtWidgets.QPushButton(self.centralWidget)
        self.abrir_modelo.setGeometry(QtCore.QRect(340, 80, 100, 27))
        self.abrir_modelo.setObjectName("abrir_modelo")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 241, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(70, 190, 231, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 210, 300, 27))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.abrir_participantes = QtWidgets.QPushButton(self.centralWidget)
        self.abrir_participantes.setGeometry(QtCore.QRect(340, 210, 100, 27))
        self.abrir_participantes.setObjectName("abrir_participantes")
        self.gerar_certificado = QtWidgets.QPushButton(self.centralWidget)
        self.gerar_certificado.setGeometry(QtCore.QRect(59, 380, 141, 27))
        self.gerar_certificado.setObjectName("gerar_certificado")
        self.arquivos_processados = QtWidgets.QListWidget(self.centralWidget)
        self.arquivos_processados.setGeometry(QtCore.QRect(590, 90, 256, 192))
        self.arquivos_processados.setObjectName("arquivos_processados")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 310, 300, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.abrir_saida = QtWidgets.QPushButton(self.centralWidget)
        self.abrir_saida.setGeometry(QtCore.QRect(340, 310, 100, 27))
        self.abrir_saida.setObjectName("abrir_saida")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(70, 280, 111, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(610, 70, 211, 17))
        self.label_4.setObjectName("label_4")
        self.checar_certificado = QtWidgets.QPushButton(self.centralWidget)
        self.checar_certificado.setGeometry(QtCore.QRect(220, 380, 151, 27))
        self.checar_certificado.setObjectName("checar_certificado")
        Gerador.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Gerador)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 974, 25))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuGerador_de_Certificados = QtWidgets.QMenu(self.menuBar)
        self.menuGerador_de_Certificados.setObjectName("menuGerador_de_Certificados")
        self.menuAbrir = QtWidgets.QMenu(self.menuGerador_de_Certificados)
        self.menuAbrir.setObjectName("menuAbrir")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSobre = QtWidgets.QMenu(self.menuBar)
        self.menuSobre.setObjectName("menuSobre")
        Gerador.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Gerador)
        self.mainToolBar.setObjectName("mainToolBar")
        Gerador.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Gerador)
        self.statusBar.setObjectName("statusBar")
        Gerador.setStatusBar(self.statusBar)
        self.actionPet = QtWidgets.QAction(Gerador)
        self.actionPet.setObjectName("actionPet")
        self.actionCriador = QtWidgets.QAction(Gerador)
        self.actionCriador.setObjectName("actionCriador")
        self.actionModelo = QtWidgets.QAction(Gerador)
        self.actionModelo.setObjectName("actionModelo")
        self.actionParticipantes = QtWidgets.QAction(Gerador)
        self.actionParticipantes.setObjectName("actionParticipantes")
        self.menuAbrir.addSeparator()
        self.menuAbrir.addAction(self.actionModelo)
        self.menuAbrir.addAction(self.actionParticipantes)
        self.menuGerador_de_Certificados.addAction(self.menuAbrir.menuAction())
        self.menuSobre.addAction(self.actionPet)
        self.menuSobre.addAction(self.actionCriador)
        self.menuBar.addAction(self.menuGerador_de_Certificados.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(Gerador)
        QtCore.QMetaObject.connectSlotsByName(Gerador)

    def retranslateUi(self, Gerador):
        _translate = QtCore.QCoreApplication.translate
        Gerador.setWindowTitle(_translate("Gerador", "Gerador de Certificados"))
        self.lineEdit.setToolTip(_translate("Gerador", "Arquivo modelo do Latex"))
        self.abrir_modelo.setText(_translate("Gerador", "Abrir"))
        self.label.setText(_translate("Gerador", "Arquivo modelo do Latex"))
        self.label_2.setText(_translate("Gerador", "Lista de nomes dos participantes"))
        self.abrir_participantes.setText(_translate("Gerador", "Abrir"))
        self.gerar_certificado.setText(_translate("Gerador", "Gerar Certificado"))
        self.abrir_saida.setText(_translate("Gerador", "Abrir"))
        self.label_3.setText(_translate("Gerador", "Pasta de saída"))
        self.label_4.setText(_translate("Gerador", "Lista de arquivos processados"))
        self.checar_certificado.setText(_translate("Gerador", "Checar Certificados"))
        self.menuBar.setToolTip(_translate("Gerador", "Menus aqui"))
        self.menuGerador_de_Certificados.setTitle(_translate("Gerador", "Arquivo"))
        self.menuAbrir.setTitle(_translate("Gerador", "Abrir"))
        self.menuFile.setTitle(_translate("Gerador", "Editar"))
        self.menuSobre.setTitle(_translate("Gerador", "Ajuda"))
        self.actionPet.setText(_translate("Gerador", "PET"))
        self.actionCriador.setText(_translate("Gerador", "Criador"))
        self.actionModelo.setText(_translate("Gerador", "Modelo"))
        self.actionModelo.setShortcut(_translate("Gerador", "Ctrl+M"))
        self.actionParticipantes.setText(_translate("Gerador", "Participantes"))
        self.actionParticipantes.setShortcut(_translate("Gerador", "Ctrl+P"))

